# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    v4l2loopback
  ];
  boot.extraModprobeConfig = ''
    options v4l2loopback devices=1 video_nr=1 card_label="OBS Cam" exclusive_caps=1
  '';
  security.polkit.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/74fba569-c16e-49b7-a679-861672526532";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "defaults" ];
    };
  
  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/c8a988dc-a718-47ac-809d-a9c711a4d535";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "compress=zstd" "defaults" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9312-BEA2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/kc3000" =
   { device = "/dev/disk/by-uuid/76e10bda-aeb0-4c0c-a183-cdf6a6a9441e";
     fsType = "btrfs";
     options = [ "compress=zstd" "defaults" ];                                                                                                                                                                                                                                                                                          
   };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3b05bb1d-6aa2-4517-86ac-939d28db7dc0";
      fsType = "btrfs";
      options = [ "compress=zstd" "defaults" ];                                                                                                                                                                                                                                                                                          
    };

  fileSystems."/mnt/sn850x" =
    { device = "/dev/disk/by-uuid/226c499d-e6e3-472c-a1a4-bc3372d9a8bb";
      fsType = "btrfs";
      options = [ "compress=zstd" "defaults" ];                                                                                                                                                                                                                                                                                          
    };

  fileSystems."/mnt/sn750" = 
    {                                                                                                                                                                                                                                                                                                         
      device = "/dev/disk/by-uuid/e8b4207b-0a1c-422b-b2f7-569419fb0b94";                                                                                                                                                                                                                                                             
      fsType = "btrfs";                                                                                                                                                                                                                                                                                                                  
      options = [ "compress=zstd" "defaults" ];                                                                                                                                                                                                                                                                                          
    }; 

  swapDevices =
    [ { device = "/dev/disk/by-uuid/107441f8-5cf0-4573-822b-6950437e4788"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp12s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp13s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
